#!/bin/bash

module load intel/2017.01
export I_MPI_F90=ifort

case $2 in 
'-g')
	dbg='-g -debug all -traceback  -check bounds -debug inline-debug-info'
	;;
'')
	dbg=''
	;;
esac



# compile
mpif90 -i4 -r8 $dbg -c ./source/schemes.f90 
mpif90 -i4 -r8 $dbg -c ./source/prep.f90
mpif90 -i4 -r8 $dbg -c ./source/paralrts.f90
mpif90 -i4 -r8 $dbg -c ./source/paral3.f90

# link
mpif90 -i4 -r8 $dbg paral3.o paralrts.o prep.o schemes.o -o $1

rm *.o
