#!/bin/bash

mkdir data
dr=data

# 5 seconds, CFL ~1.0
CFL=0.928125000000000
N=10
./adv gauss upwind $CFL 100 $N $dr/g_upw_ca10_t5.dat $dr/stats.dat
./adv gauss laxfr $CFL 100 $N $dr/g_lfr_ca10_t5.dat $dr/stats.dat
./adv gauss laxwe $CFL 100 $N $dr/g_lwe_ca10_t5.dat $dr/stats.dat
./adv gauss macco $CFL 100 $N $dr/g_mac_ca10_t5.dat $dr/stats.dat
./adv gauss ftcs $CFL 100 $N $dr/g_ftc_ca10_t5.dat $dr/stats.dat

# 5 seconds, CFL ~0.5
CFL=0.488486842105263
N=19
./adv gauss upwind $CFL 100 $N $dr/g_upw_ca05_t5.dat $dr/stats.dat
./adv gauss laxfr $CFL 100 $N $dr/g_lfr_ca05_t5.dat $dr/stats.dat
./adv gauss laxwe $CFL 100 $N $dr/g_lwe_ca05_t5.dat $dr/stats.dat
./adv gauss macco $CFL 100 $N $dr/g_mac_ca05_t5.dat $dr/stats.dat
./adv gauss ftcs $CFL 100 $N $dr/g_ftc_ca05_t5.dat $dr/stats.dat


# 10 seconds, CFL ~1.0
CFL=0.928125000000000
N=20
./adv gauss upwind $CFL 100 $N $dr/g_upw_ca10_t10.dat $dr/stats.dat
./adv gauss laxfr $CFL 100 $N $dr/g_lfr_ca10_t10.dat $dr/stats.dat
./adv gauss laxwe $CFL 100 $N $dr/g_lwe_ca10_t10.dat $dr/stats.dat
./adv gauss macco $CFL 100 $N $dr/g_mac_ca10_t10.dat $dr/stats.dat
./adv gauss ftcs $CFL 100 $N $dr/g_ftc_ca10_t10.dat $dr/stats.dat

# 10 seconds, CFL ~0.5
CFL=0.488486842105263
N=38
./adv gauss upwind $CFL 100 $N $dr/g_upw_ca05_t10.dat $dr/stats.dat
./adv gauss laxfr $CFL 100 $N $dr/g_lfr_ca05_t10.dat $dr/stats.dat
./adv gauss laxwe $CFL 100 $N $dr/g_lwe_ca05_t10.dat $dr/stats.dat
./adv gauss macco $CFL 100 $N $dr/g_mac_ca05_t10.dat $dr/stats.dat
./adv gauss ftcs $CFL 100 $N $dr/g_ftc_ca05_t10.dat $dr/stats.dat
